import os
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import cm

os.makedirs("build", exist_ok=True)
PDF_PATH = "build/cancanary_dev_manual.pdf"

styles = getSampleStyleSheet()
doc = SimpleDocTemplate(
    PDF_PATH,
    pagesize=A4,
    leftMargin=2 * cm,
    rightMargin=2 * cm,
    topMargin=2 * cm,
    bottomMargin=2 * cm,
)
story = []
story.append(Paragraph("Newsletter Dev Manual (Multi-Topic)", styles["Title"]))
story.append(Spacer(1, 12))
story.append(
    Paragraph(
        "This PDF is generated by CI and includes rendered diagrams from docs/uml.",
        styles["Normal"],
    )
)
story.append(Spacer(1, 12))
for name in ("class", "flow", "usecase"):
    svg_path = f"build/diagrams/{name}.svg"
    if os.path.exists(svg_path):
        story.append(Paragraph(name.title(), styles["Heading2"]))
        story.append(Paragraph(f"(Rendered: {svg_path})", styles["Code"]))
        story.append(Spacer(1, 6))
doc.build(story)
print(PDF_PATH)
