name: deploy-matrix
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        topic: [ev, tfktcl, tfitconsult]
    steps:
      - uses: actions/checkout@v4
      - name: Set topic
        run: echo "TOPIC_SLUG=${{ matrix.topic }}" >> $GITHUB_ENV
      - name: Docker meta
        run: echo "Building for topic=${{ matrix.topic }}"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push API
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.api
          push: true
          tags: ghcr.io/${{ github.repository }}/api:${{ matrix.topic }}-latest
      - name: Build & Push Worker
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.worker
          push: true
          tags: ghcr.io/${{ github.repository }}/worker:${{ matrix.topic }}-latest
